### ISSUE TITLE
Extend response with rate limit X-headers

### ISSUE THREAD

**Issue by bravo-kernel** [UseMuffin/Throttle#10]
I think the plugin could benefit of sending (optional) X-headers containing throttling information like Github does (limit, remaining, reset in image below).

Please let me know if this can make it in so I can create a PR.

![api-schema](https://cloud.githubusercontent.com/assets/230500/8893866/315132ca-33a2-11e5-8bea-3d7c772ff846.png)

**Comment by jadb** [comment]
Yes - i only see it as an improvement. Just make sure one can turn it off?

**Comment by bravo-kernel** [comment]
Implemented through #12
