### ISSUE TITLE
Headers not set for error responses

### ISSUE THREAD

**Issue by bravo-kernel** [UseMuffin/Throttle#13]
The rate limiting headers are not set when errors occur (test with 404 and 412 validation). 

Is this expected behavior? If so, I will add a note to the docs.

**Comment by ADmad** [comment]
This is expected since exception renderer generates a new response instance and all existing settings are lost.

**Comment by bravo-kernel** [comment]
So either accept the missing headers or create a custom exception renderer, right?

A generic approach would be nice since I just bumped into the similar case with a CORS DispatchFilter (making it impossible to send correct cors reply without the correct headers). I can imagine this could occur in more places.

**Comment by bravo-kernel** [comment]
Just tested by triggering some errors and it indeed seems isolated to just the missing headers... the rate limit counter is updated as expected so the throttling mechanism is solid. Closing while I think up a mention in the readme.
