### ISSUE TITLE
Cache file not being created?

### ISSUE THREAD

**Issue by bravo-kernel** [UseMuffin/Throttle#2]
Just added plain Muffin/Throttle and keep getting 'rate limit exceeded'. I believe because a cache file is not being created. Can you confirm a cache file should appear?

**Comment by ADmad** [comment]
Have you configured cache config `throttle`? If not what cache engine does your `default` config use?

**Comment by bravo-kernel** [comment]
As discussed in the #muffin channel:
- I am using the default File cache provided by app-skeleton
- I did not configure a `throttle` cache engine

**Feedback received**: throttle uses Cache::increment() and atomic increments can't be done for FileEngine. Though you should have got an exception.

https://github.com/UseMuffin/Throttle/blob/master/src/Routing/Filter/ThrottleFilter.php#L63
https://github.com/cakephp/cakephp/blob/master/src/Cache/Engine/FileEngine.php#L359

@todo investigate why the exception wasn't thrown

**Comment by bravo-kernel** [comment]
Solved with PR https://github.com/UseMuffin/Throttle/pull/3
