### ISSUE TITLE
Is it possible to have multiple configurations with different rates?

### ISSUE THREAD

**Issue by beecrowd** [UseMuffin/Throttle#20]
I would like to have two or three rates, based on a group. Is it possible to have multiple configurations with different rates or this value is fixed for all?

**Comment by ADmad** [comment]
Nope, varying rates are currently not possible.

**Comment by chrisShick** [comment]
I wonder if this is something we could think about in terms of perhaps a strategy type situation. One that would allow the identifier to be customized to decide which configuration to use?

**Comment by ADmad** [comment]
Besides URL what other criteria would you use to create groups?

**Comment by chrisShick** [comment]
@ADmad Apparently, this never got off. Using the middleware after the session middle, couldn't there have a hook that allows for the throttle to be set differently based on the developer's needs?

**Comment by ADmad** [comment]
With routing based middleware support now available in core you can setup throttle with different configs for each routing scope.

**Comment by chrisShick** [comment]
That will only base it on the routing though. What if, for example, there are two different groups of users that use the same api but I want to have a higher limit because it is a paying customer? There would then need to be a "hook" that can be used to determine different configs for different "groups" using the same route.

**Comment by chrisShick** [comment]
Well, I guess you could technically create several throttle middlewares and only apply then under each case.

**Comment by HorlogeSkynet** [comment]
Hi @ADmad, 'hope you doing okay.

Can you confirm that you already did something like this with routing scopes ?
I tried to instanciate two different Throttle middlewares on different scopes, but visiting each scope keep decrementing the same value...
As the two instances use the same cache, I guess it comes from this.

Do you have a solution for this ?

Bye,
Thanks again :wave: 


EDIT & Idea : I've thought about modifying the `identifier` based on the **IP** and the **scope** visited but maybe I am missing a cleaner way to do this ? :thinking:

**Comment by ADmad** [comment]
> Do you have a solution for this ?

Use different cache prefixes for different instances of middleware?

**Comment by HorlogeSkynet** [comment]
Hmm... Yes but AFAIK, only the `identifier` part of the cache `prefix` could be properly configured : https://github.com/UseMuffin/Throttle/blob/9eef7ed2f23a44297df4580a4fcb76d804db6a81/src/ThrottleTrait.php#L98
But the `identifier` is also the only part used to distinguish each user...

Was my "EDIT & Idea" above correct then ? Or maybe I still don't get the big picture here :thinking:

**Comment by smarek** [comment]
@HorlogeSkynet don't know how you did solve your situation, but your wishes might have been provided by #33 care to check it out?

**Comment by HorlogeSkynet** [comment]
@smarek We actually didn't. I'll try to check it out if it gets merged & released, thanks.

**Comment by ADmad** [comment]
https://github.com/UseMuffin/Throttle/pull/38 will allow modifying the throttling info based on current request. Check the `testProcessWithThrottleCallback()` test case for an example.

**Comment by HorlogeSkynet** [comment]
Any chance to get it for Cake 3.X branches ?

**Comment by ADmad** [comment]
> Any chance to get it for Cake 3.X branches ?

No.

**Comment by smarek** [comment]
@HorlogeSkynet #33 is pretty much functional, however no upstream support from @ADmad will be provided, so you can use either what I have in https://github.com/smarek/Throttle or merge it in your repository, because no further Throttle development for 3.x will be done here

**Comment by ADmad** [comment]
New CakePHP 4 compatible major version v2 (currently beta) now allows multiple rate limits, checkout readme for details.
