### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by chrisShick** [UseMuffin/Throttle#21]
Any plans to make this work with middleware now that DispatchFilters are deprecated?

**Comment by ADmad** [comment]
Pull requests are welcome :)

**Comment by chrisShick** [comment]
I believe I might be a little interested :D

**Comment by ADmad** [comment]
Give it a go, I will be happy to review :)

**Comment by chrisShick** [comment]
@ADmad I just finished the middlware for this :) on my fork of this. As soon as I get through writing the test, I will create a pull request. How do you want to do deal with that? It requires an updated version of cakephp. A new branch?

**Comment by ADmad** [comment]
Just make a PR to master once you are ready with the tests to begin with.

**Comment by bravo-kernel** [comment]
Sweet, I'm very curious how this will look. Thank you for stepping up mr. @chrisshick

**Comment by chrisShick** [comment]
@ADmad Good deal.
@bravo-kernel You are welcome. Although, A LOT of the work was already done by @ADmad so all I can really take credit for is porting it over lol

**Comment by chrisShick** [comment]
Just submitted the pull request @ADmad and @bravo-kernel [#22](https://github.com/UseMuffin/Throttle/pull/22)

**Comment by chrisShick** [comment]
I am closing this now that it has been merged to master :D
