### ISSUE TITLE
Ability to set extra custom headers for response

### ISSUE THREAD

**Issue by HorlogeSkynet** [UseMuffin/Throttle#26]
Hi there !

A simple question (I'm ready to implement it if needed), would it be possible to let the developer set extra headers for the response sent, once the limitation is reached ?
For instance, if we want to throw a JSON-encoded message to the user, it'd be cool if the `Content-Type` was set to `application/json`.

What I would like to do currently is something like :

```php
$routes->registerMiddleware('throttle', new ThrottleMiddleware([
    'limit'      => XXX,
    'interval'   => '+XXX minutes',
    'message'    => json_encode(['error' => 'A typical error message...']),
    'headers' => [
        'limit'     => 'X-RateLimit-Limit',
        'remaining' => 'X-RateLimit-Remaining',
        'reset'     => 'X-RateLimit-Reset',
        'type'      => 'json'
    ]
]));
```

Do you think it's a good idea ?

Thanks,
Bye :wave:

**Comment by ADmad** [comment]
Sounds good.

**Comment by HorlogeSkynet** [comment]
Closing here as PR (#27) is on its way.
