### ISSUE TITLE
Redis support?

### ISSUE THREAD

**Issue by smarek** [UseMuffin/Throttle#35]
According to documentation, cache engine supporting atomic operations and increments, must be used.
I've tried to use RedisEngine with middleware config `'interval' => '+1 minutes'`, but it seems that cached counts do not expire

RedisEngine has it's own cache configuration 'duration', number of seconds the items in cache last

However providing number of seconds as 'interval' configuration to ThrottleMiddleware will fail on `_touch()` method parsing it as `strtotime($this->getConfig('interval'), time())`

Additionaly, TTL of _expires cache item is not bumped, because except for initial configuration, it's not touched the same way as the counter cache. So the whole throttle logic waits for both items to expire in cache, be evicted, and then allows for new non-throttled request. Which means **as long as the requests are made periodically, faster than cache expiration, throttle will never, after initial limit hit, allow the request be made**, and I'm not sure if that is intentional

I'm not sure how to fix that, so I'm writing this issue instead

**Comment by ADmad** [comment]
> Which means as long as the requests are made periodically, faster than cache expiration, throttle will never, after initial limit hit, allow the request be made, and I'm not sure if that is intentional

Isn't that how throttling is supposed to work? Once you exceed the limit you can't make a request before "cool down" period expire.

**Comment by smarek** [comment]
Yes, but I kinda expected the cool down to not force me to stop trying, i'm cool with the way it works currently, because ever-running bruteforce attack, will be deflected with current behavior completely, other variant would allow some requests to pass from time-to-time.

Anyway, that does not solve the docs ambiguousness on clash between 'interval' and 'duration' configs, would you mind addressing that please?

**Comment by ADmad** [comment]
The docs don't mention anything about cache duration. I personally think it's obvious that the value for `duration` in cache engine config should be larger than or equal to the `interval` used in the middleware. But you can add a clarification in the readme if you like.

**Comment by smarek** [comment]
Exactly, no mention that `interval` config is used to configure `duration` of the cache engine

https://github.com/UseMuffin/Throttle/blob/cake-4.x/src/Middleware/ThrottleMiddleware.php#L151

and also be parsed / used as expiration marker in cache write here

https://github.com/UseMuffin/Throttle/blob/cake-4.x/src/Middleware/ThrottleMiddleware.php#L193

If you use RedisEngine and provide `interval` as int, mentioned `strtotime` will fail hard
If you use RedisEngine and provide `interval` as string like `+1 hour`, it will never use built-in expiration of keys, because it expects the `duration` to be int, not string

**Comment by ADmad** [comment]
Hmm.. `CacheInterface::set()` has an argument for TTL, so if that was used we wouldn't even need to maintain a separate key to hold the expiry time.

Unfortunately `Cache::write()` doesn't have an argument for TTL. So I would rather use a `CacheInterface` interface directly to deal with this issue.

**Comment by ADmad** [comment]
Instead of using `Cache::write()` use `Cache::pool` to get the engine instance and then use `$engin->set()`.

**Comment by ADmad** [comment]
Err we would still need to use separate key to store the interval since the number of requests is updated using `increment()` which doesn't have a TTL argument.

**Comment by ADmad** [comment]
Disregard whatever I said above. Let's start fresh.

The value of `interval` is used for cache engine's duration config only if the haven't already created a cache config named `throttle`. If you have created a cache config named `throttle` yourself then the value of `interval` is only stored to send response headers when rate limit is exceeded.

**Comment by smarek** [comment]
Got it, also I found where I understood bad the CacheEngine init/config sequence, CacheEngine will convert string as
 `$this->_config['duration'] = strtotime($this->_config['duration']) - time();`
Still i feel, that it was not meant to be that `identifier_expires` key in cache expires possibly hours before the `identifier` key expires

```
127.0.0.1:6379> KEYS throttle_*
1) "throttle_ip_expires"
2) "throttle_ip"
127.0.0.1:6379> TTL throttle_ip_expires
(integer) 58
127.0.0.1:6379> TTL throttle_ip
(integer) 57
// wait a bit, make requests to frontend, query again
127.0.0.1:6379> TTL throttle_ip_expires
(integer) -2
127.0.0.1:6379> TTL throttle_ip
(integer) 55
```

the `identifier` will get TTL bumped, because it gets updated, `identifier_expires` won't because it's not touched after initial set
and the throttle then will ultimately depend on CacheEngine duration/ttl expiration instead of doing anything useful with `identifier_expires` data, which will get lost

**Comment by ADmad** [comment]
`identifier_expires` key is only for storing value for `X-RateLimit-Reset` header, to show the timestamp when the rate limit will be reset. It serves no other purpose and it's value doesn't need to be bumped. Actual cache expiry will depend on duration/ttl config of your cache engine (which ideally should be same as the `interval`).

**Comment by smarek** [comment]
but since the data in `identifier_expires` is long-gone and the cool-down period won't start unless you stop requesting the resource, it's invalid. You send `X-RateLimit-Reset` to indicate when the rate-limit resets, but the actual reset won't happen at that time, if you keep the requests coming.
would be more meaningful to bump both the cache key/ttl and the value with each request, that shifts the start of cooldown period, because that should also change the `x-ratelimit-reset` header value

anyway RedisEngine is obviously supported, and if i'm cool, and i'm, with the whole **stop doing requests, to start cooldown** thing, this ticket might be closed

**Comment by ADmad** [comment]
> You send X-RateLimit-Reset to indicate when the rate-limit resets, but the actual reset won't happen at that time, if you keep the requests coming.

The reset will happen when the TTL for the `identifier` key is exceeded. Once you exceed the rate limit you don't have to wait till the full duration of expiry. The time you have to wait to do the next request depends on when you made the first request within the interval.

Now there might be other ways to handle the cool down period but this is the way it's done by this plugin.

Closing the issue as your original query regarding RedisEngine is clarified.
