### ISSUE TITLE
Export rate limit check login in a separated class for using out of a middleware

### ISSUE THREAD

**Issue by doshu** [UseMuffin/Throttle#48]
This is a enchantment request.
If the rate limit check logic will be exported in a separated class, this package can be used to throttling a specific code portion.
for example we can throttle a failed login.

**Comment by asgraf** [comment]
> This is a enchantment request. If the rate limit check logic will be exported in a separated class, this package can be used to throttling a specific code portion. for example we can throttle a failed login.

You can already do that by applying this middleware to specific scope with only specific actions (like login action):
https://book.cakephp.org/5/en/development/routing.html#route-scoped-middleware

**Comment by ADmad** [comment]
Middlewares can now be attached in controllers too https://book.cakephp.org/5/en/controllers.html#controller-middleware
