### ISSUE TITLE
Packagist not serving most recent version

### ISSUE THREAD

**Issue by bravo-kernel** [UseMuffin/Throttle#9]
Latest version served/shown by Packagist is 45d28271d4c50cf29676488983fe68a535039865 instead of most the recent commit. Something not updating there?

**Comment by jadb** [comment]
ping @ADmad

**Comment by ADmad** [comment]
Packagist hook has been setup for the repo. Don't know why it still complains about package not being auto updated :angry:

**Comment by ADmad** [comment]
Should be fixed now. Error message is gone.
